export const constellations = [
  {
    id: "lyra",
    name: "Lyra",
    position: { x: 14, y: 44 },

    members: [
      {
        id: "miriale",
        name: "Miriale",
        screenshot: "images/Miriale.png",
        url: "https://m1riale.github.io/your-tribe-profile-card/",
        position: { x: 18, y: 27 },
      },
      {
        id: "sun",
        name: "Sun",
        screenshot: "images/Sun.png",
        url: "https://stldevelopment.github.io/your-tribe-profile-card/",
        position: { x: 43, y: 16 },
      },
      {
        id: "justin",
        name: "Justin",
        screenshot: "images/project-three.png",
        url: "https://justinverbon1234.github.io/introwebsite/",
        position: { x: 73, y: 24 },
      },
      {
        id: "britt",
        name: "Britt",
        screenshot: "images/Britt.png",
        url: "https://brittvegt.github.io/your-tribe-profile-card/",
        position: { x: 84, y: 48 },
      },
      {
        id: "noey",
        name: "Noey",
        screenshot: "images/Noey.png",
        url: "https://noeyoo26.github.io/your-tribe-profile-card/",
        position: { x: 56, y: 42 },
      },
      {
        id: "rabia",
        name: "Rabia",
        screenshot: "images/Rabia.png",
        url: "https://rabiaarkan.github.io/your-tribe-profile-card/",
        position: { x: 28, y: 54 },
      },
      {
        id: "beyza",
        name: "Beyza",
        screenshot: "images/Beyza.png",
        url: "https://beyzaarkan.github.io/your-tribe-profile-card/",
        position: { x: 15, y: 76 },
      },
      {
        id: "xin",
        name: "Xin",
        screenshot: "images/xin.png",
        url: "https://xinjuliette.github.io/your-tribe-profile-card/",
        position: { x: 50, y: 72 },
      },
    ],
  },

  {
    id: "aurora",
    name: "Aurora",
    position: { x: 28, y: 80 },

    members: [
      {
        id: "ahmet",
        name: "Ahmet",
        screenshot: "images/Ahmet.png",
        url: "https://temhasene.github.io/your-tribe-profile-card/",
        position: { x: 23, y: 22 },
      },
      {
        id: "aliya",
        name: "Aliya",
        screenshot: "images/Aliya.png",
        url: "https://aliyaharding.github.io/your-tribe-profile-card/",
        position: { x: 48, y: 11 },
      },
      {
        id: "aya",
        name: "Aya",
        screenshot: "images/Aya.png",
        url: "https://ayalefevere.github.io/your-tribe-profile-card/",
        position: { x: 78, y: 19 },
      },
      {
        id: "bounyad",
        name: "Bounyad",
        screenshot: "images/Visite.png",
        url: "https://crazeygruy.github.io/your-tribe-profile-card/",
        position: { x: 86, y: 43 },
      },
      {
        id: "celeste",
        name: "Celeste",
        screenshot: "images/Celeste.png",
        url: "https://celeste0012.github.io/your-tribe-profile-card/",
        position: { x: 61, y: 37 },
      },
      {
        id: "chahed",
        name: "Chahed",
        screenshot: "images/Chahed.png",
        url: "https://chahedddd.github.io/your-tribe-profile-card/",
        position: { x: 33, y: 49 },
      },
      {
        id: "david",
        name: "David",
        screenshot: "images/David.png",
        url: "https://davidoo379.github.io/your-tribe-profile-card/",
        position: { x: 20, y: 71 },
      },
      {
        id: "emmanuel",
        name: "Emmanuel",
        screenshot: "images/Emmanuel.png",
        url: "https://emmatje.github.io/your-tribe-profile-card/",
        position: { x: 55, y: 67 },
      },
    ],
  },

  {
    id: "nexus",
    name: "Nexus",
    position: { x: 50, y: 14 },

    members: [
      {
        id: "hajar",
        name: "Hajar",
        screenshot: "images/IMAGE-10.png",
        url: "https://h-mti.github.io/your-tribe-profile-card/",
        position: { x: 24, y: 21 },
      },
      {
        id: "jarellsa",
        name: "Jarellsa",
        screenshot: "images/Jarellsa.png",
        url: "https://js5603.github.io/your-tribe-profile-card/",
        position: { x: 52, y: 15 },
      },
      {
        id: "joost",
        name: "Joost",
        screenshot: "images/Joost.png",
        url: "https://s2108887.github.io/your-tribe-profile-card/",
        position: { x: 80, y: 25 },
      },
      {
        id: "lois",
        name: "Lois",
        screenshot: "images/Lois.png",
        url: "https://loisaantjes.github.io/your-tribe-profile-card/",
        position: { x: 85, y: 53 },
      },
      {
        id: "lou",
        name: "Lou",
        screenshot: "images/Lou.png",
        url: "https://louavb.github.io/your-tribe-profile-card/",
        position: { x: 57, y: 46 },
      },
      {
        id: "lyndsey",
        name: "Lyndsey",
        screenshot: "images/lyndsey.png",
        url: "https://lyndsey07.github.io/your-tribe-profile-card/",
        position: { x: 30, y: 56 },
      },
      {
        id: "lyanne",
        name: "Lyanne",
        screenshot: "images/Lyanne.png",
        url: "https://lyannebos.github.io/your-tribe-profile-card/",
        position: { x: 47, y: 75 },
      },
    ],
  },

  {
    id: "vela",
    name: "Vela",
    position: { x: 86, y: 40 },

    members: [
      {
        id: "melissa",
        name: "Melissa",
        screenshot: "images/Melissa.png",
        url: "https://melis5016.github.io/your-tribe-profile-card/",
        position: { x: 19, y: 22 },
      },
      {
        id: "mika",
        name: "Mika",
        screenshot: "images/Mika.png",
        url: "https://mikahartono007.github.io/your-tribe-profile-card/",
        position: { x: 47, y: 16 },
      },
      {
        id: "queeny",
        name: "Queeny",
        screenshot: "images/queeny.png",
        url: "https://queeny2003.github.io/your-tribe-profile-card/",
        position: { x: 75, y: 26 },
      },
      {
        id: "rayhana",
        name: "Rayhana",
        screenshot: "images/Rayhana.png",
        url: "https://rayhana7.github.io/your-tribe-profile-card/",
        position: { x: 82, y: 54 },
      },
      {
        id: "rick",
        name: "Rick",
        screenshot: "images/Rick.png",
        url: "https://rickd377.github.io/your-tribe-profile-card/",
        position: { x: 60, y: 47 },
      },
      {
        id: "rosa",
        name: "Rosa",
        screenshot: "images/Rosa.png",
        url: "https://rosavandenbos.github.io/your-tribe-profile-card/",
        position: { x: 25, y: 57 },
      },
      {
        id: "rowynn",
        name: "Rowynn",
        screenshot: "images/Rowynn.png",
        url: "https://rowynn-eu.github.io/fdnd-profile-card/",
        position: { x: 42, y: 76 },
      },
    ],
  },

  {
    id: "orbit",
    name: "Orbit",
    position: { x: 72, y: 82 },

    members: [
      {
        id: "sam",
        name: "Sam",
        screenshot: "images/Sam.png",
        url: "https://sambalsamss.github.io/your-tribe-profile-card/",
        position: { x: 22, y: 23 },
      },
      {
        id: "savannah",
        name: "Savannah",
        screenshot: "images/savannah.png",
        url: "https://savannahvdheld.github.io/your-tribe-profile-card/",
        position: { x: 50, y: 17 },
      },
      {
        id: "sophie",
        name: "Sophie",
        screenshot: "images/Sophie.png",
        url: "https://sophieediepenmaat.github.io/your-tribe-profile-card/",
        position: { x: 78, y: 27 },
      },
      {
        id: "thijs",
        name: "Thijs",
        screenshot: "images/Thijs.jpg",
        url: "https://thijs-fdnd.github.io/your-tribe-profile-card/",
        position: { x: 85, y: 55 },
      },
      {
        id: "wesley",
        name: "Wesley",
        screenshot: "images/Wesley.png",
        url: "https://toonicwesley.github.io/your-tribe-profile-card/",
        position: { x: 60, y: 55 },
      },
      {
        id: "younes",
        name: "Younes",
        screenshot: "images/Younes.png",
        url: "https://youneselkharraz.github.io/i-love-web/",
        position: { x: 28, y: 58 },
      },
      {
        id: "youssra",
        name: "Youssra",
        screenshot: "images/Youssra.png",
        url: "https://y0usss.github.io/your-tribe-profile-card/",
        position: { x: 45, y: 77 },
      },
      {
        id: "jesper",
        name: "Jesper",
        screenshot: "images/Jesper.png",
        url: "https://jesperkoning1.github.io/your-tribe-profile-card/",
        position: { x: 75, y: 62 },
      },
    ],
  },
];
